development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: holisticlife_development
  pool: 5
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: holisticlife_test
  pool: 5
  host: localhost
# socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: holisticlife_production
  pool: 5
  host: localhost
  username:
  password: